# Site settings
title: Seychelles
clients:
  - name: Qatar Airways
    link: ""
    img: qatar-airways.svg
  - name: Seychelles
    link: ""
    img: seychelles.svg

core-se-link: https://it.secretescapes.com/offerte-in-corso
description: >
  Chiudi gli occhi e immagina un luogo in cui la natura è rigogliosa e ancora incontaminata, il clima è praticamente perfetto tutto l’anno e dove ognuna delle 115 isole presenti nasconde almeno una spiaggia da sogno. Adesso riapri gli occhi e preparati a esplorare con noi il meraviglioso arcipelago delle isole Seychelles.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/seychelles" # the subpath of your site, e.g. /blog/
img:     "/seychelles/_assets/img"
css:     "/seychelles/_assets/css"
js:      "/seychelles/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed